apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-finale
  labels:
    app: capstone-finale
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-finale
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-finale
    spec:
      containers:
        - image: mulero44/capstone-finale
          imagePullPolicy: Always
          name: capstone-finale
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-finale
  labels:
    app: capstone-finale
spec:
  type: LoadBalancer
  selector:
    app: capstone-finale
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
